# Welcome to Jekyll!

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://misskukuua.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

theme: jekyll-theme-primer


#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# navigation:
#   - title: "Home"
#     url: "/"
#   - title: "About"
#     url: "/my/"
#   - title: "Contact"
#     url: "/contact/"

sass:
  style: compressed # or :expanded for debugging
  load_paths:
    - assets/css
