source "https://rubygems.org"

# Use the GitHub Pages gem which includes all dependencies
gem 'github-pages', group: :jekyll_plugins

# This is the default theme for new Jekyll sites. This is automatically handled by github-pages.
# gem "minima", "~> 2.5"

# If you have any additional plugins, put them here.
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "webrick"
gem "csv"
gem "faraday-retry"


